name: "Build"
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: ebubear
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: '(-source$|\.tf$)'
    - run: nix-build nix -A bear
